Repository teacher-for-boss/teacher-for-boss-android, pull requests merged in 2024-08, with the labels that each got.

#117 [Fix/profile] 프로필 API 수정
  app/src/main/java/com/company/teacherforboss/data/datasource.remote/MemberRemoteDataSource.kt
  app/src/main/java/com/company/teacherforboss/data/datasourceimpl.remote/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/company/teacherforboss/data/model/request/mypage/TeacherDetailProfileRequestDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/auth/AccountResponseDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/mypage/ProfileResponseDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/mypage/teacher_detail_profile/TeacherDetailProfileResponseDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/mypage/teacher_detail_profile/TeacherRecentAnswersResponseDto.kt
  app/src/main/java/com/company/teacherforboss/data/repositoryImpl/MemberRepositoryImpl.kt
  app/src/main/java/com/company/teacherforboss/data/service/MemberService.kt
  app/src/main/java/com/company/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/company/teacherforboss/domain/model/auth/AccountEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/common/TeacherDetailProfileRequestEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/common/TeacherProfileDetailEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/common/TeacherRecentAnswerListEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/mypage/MyPageProfileEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/repository/MemberRepository.kt
  app/src/main/java/com/company/teacherforboss/domain/usecase/Member/TeacherRecentAnswersUseCase.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/common/TeacherProfileActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/common/TeacherProfileRecentAnswerFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/common/TeacherProfileViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/main/basic/TeacherTalkMainFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/ManageAccountFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyBossProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyProfileActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyProfileViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyTeacherProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/util/base/ConstsUtils.kt
  app/src/main/res/layout/fragment_modify_teacher_profile.xml
  app/src/main/res/layout/item_teacher_profile_recent_answer.xml
Labels: 🛠️FIX🛠️, 혜원🐯, 희재🐹

#124 [fix] 티처/보스 본문확인 후 이전화면 이동 로직 설정 및 검색결과 수정
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/main/BossTalkMainViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/main/basic/BossTalkMainFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/search/BossTalkSearchActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/search/rvAdapterCardBoss.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/write/BossTalkWriteActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/answer/ShowBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/answer/TeacherTalkAnswerActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/ask/TeacherTalkAskActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/main/basic/TeacherTalkMainFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/search/TeacherTalkSearchActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/search/rvAdapterCardTeacher.kt
  app/src/main/res/layout/activity_boss_talk_search.xml
  app/src/main/res/layout/activity_teacher_talk_search.xml
  app/src/main/res/layout/fragment_boss_talk_main.xml
  app/src/main/res/layout/fragment_teacher_talk_main.xml
  app/src/main/res/values/colors.xml
Labels: 🛠️FIX🛠️, 희재🐹

#123 Fix/hw
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/boss/BossProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/common/TeacherProfileActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/common/TeacherProfileViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/main/basic/BossTalkMainFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/main/card/BossTalkMainCardAdapter.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/write/BossTalkWriteActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/write/adapter/rvAdapterImage.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/write/adapter/rvAdapterTagWrite.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/answer/TeacherTalkAnswerActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/answer/adapter/rvAdapterImageTeacherAnswer.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/ask/TeacherTalkAskActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/ask/adapter/rvAdapterCategory.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/ask/adapter/rvAdapterImageTeacherAsk.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/ask/adapter/rvAdapterTagTeacher.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/main/Category/TeacherTalkCategoryAdapter.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/main/basic/TeacherTalkMainFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/main/card/TeacherTalkCardAdapter.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyBossProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyProfileActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyProfileViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ModifyTeacherProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ProfileImageDialogModify.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ProfileImageModifyDialogFragment.kt
  app/src/main/java/com/company/teacherforboss/util/base/BindingImgAdapter.kt
  app/src/main/java/com/company/teacherforboss/util/base/ConstsUtils.kt
  app/src/main/res/layout/activity_bosstalk_write.xml
  app/src/main/res/layout/activity_teachertalk_answer.xml
  app/src/main/res/layout/activity_teachertalk_ask.xml
Labels: 🛠️FIX🛠️, 혜원🐯, 🩶REFACTOR🩶
