Repository teacher-for-boss/teacher-for-boss-android, pull requests merged in 2024-07, with the labels that each got.

#42 [feat] #29:보스톡 댓글 추천/비추천 api 구현
  app/src/main/java/com/example/teacherforboss/data/datasource.remote/CommunityRemoteDataSource.kt
  app/src/main/java/com/example/teacherforboss/data/datasourceimpl.remote/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/com/example/teacherforboss/data/model/request/community/boss/RequestBossTalkCommentLikeDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/community/boss/ResponseBossTalkCommentLikeDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/community/boss/ResponseBossTalkCommentListDto.kt
  app/src/main/java/com/example/teacherforboss/data/repository/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/service/CommunityService.kt
  app/src/main/java/com/example/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/boss/BossTalkCommentLikeRequestEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/boss/BossTalkCommentLikeResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/boss/BossTalkCommentListResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/community/boss/BossTalkCommentDisLikeUseCase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/community/boss/BossTalkCommentLikeUseCase.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/adapter/rvAdapterCommentBoss.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/adapter/rvAdapterRecommentBoss.kt
  app/src/main/res/values/strings.xml
Labels: 🩷FEAT🩷, 혜원🐯

#51 Feat/delete
  app/src/main/java/com/example/teacherforboss/data/model/request/community/teacher/RequestTeacherTalkAnsDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/community/boss/ResponseBossTalkDeletePostDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/community/teacher/ResponseTeacherTalkAnsDto.kt
  app/src/main/java/com/example/teacherforboss/data/repository/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/service/CommunityService.kt
  app/src/main/java/com/example/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/TeacherTalkAnsResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/boss/BossTalkDeletePostResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/teacher/TeacherTalkAnsRequestEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/teacher/TeacherTalkAnsResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/community/boss/BossTalkDeletePostUseCase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/community/teacher/TeacherTalkAnsUseCase.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/adapter/rvAdapterCommentTeacher.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/dialog/DeleteBodyDialog.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/dialog/DeleteCommentDialog.kt
Labels: 🩷FEAT🩷, 찬영🐨

#60 Fix/heejae
  app/src/main/java/com/example/teacherforboss/MainActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/write/BossTalkWriteActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/answer/TeacherTalkAnswerActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/ask/TeacherTalkAskActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/dialog/DeleteBodyDialog.kt
  app/src/main/res/layout/activity_bosstalk_body.xml
  app/src/main/res/layout/activity_bosstalk_write.xml
  app/src/main/res/layout/rv_item_comment_boss.xml
Labels: 🛠️FIX🛠️, 희재🐹

#68 [Feat] 티처 상세 프로필 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teacherforboss/domain/model/common/TeacherProfileDetailEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/common/TeacherRecentAnswerListEntity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileFragmentStateAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileInfoFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileInfoKeywordAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileInfoKeywordViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileRecentAnswerAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileRecentAnswerFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileRecentAnswerViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/res/drawable/all_arrow_back_24.xml
  app/src/main/res/drawable/background_radius200_purple100.xml
  app/src/main/res/drawable/background_radius4_purple100_300.xml
  app/src/main/res/drawable/background_radius8_stroke_gray200.xml
  app/src/main/res/drawable/btn_option.png
  app/src/main/res/drawable/ic_back_24.xml
  app/src/main/res/drawable/ic_menu_24.xml
  app/src/main/res/drawable/ic_star_10.xml
  app/src/main/res/layout/activity_bosstalk_body.xml
  app/src/main/res/layout/activity_teacher_profile.xml
  app/src/main/res/layout/activity_teachertalk_body.xml
  app/src/main/res/layout/fragment_teacher_profile_info.xml
  app/src/main/res/layout/fragment_teacher_profile_recent_answer.xml
  app/src/main/res/layout/item_teacher_profile_keyword.xml
  app/src/main/res/layout/item_teacher_profile_recent_answer.xml
  app/src/main/res/layout/rv_item_comment_boss.xml
  app/src/main/res/layout/rv_item_comment_teacher.xml
  app/src/main/res/layout/rv_item_recomment_boss.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
Labels: 🩷FEAT🩷, 지은🎀

#71 Feat/account manage
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageAccountActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageAccountFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageSocialAccountFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/fragment_manage_account.xml
  app/src/main/res/layout/fragment_manage_social_account.xml
  app/src/main/res/layout/view_account_info.xml
  app/src/main/res/layout/view_top_app_bar_back.xml
  app/src/main/res/values/strings.xml
Labels: 🩷FEAT🩷, 찬영🐨

#79 Feat/logout
  app/src/main/java/com/example/teacherforboss/data/datasource.remote/AuthRemoteDataSource.kt
  app/src/main/java/com/example/teacherforboss/data/datasource.remote/MemberRemoteDataSource.kt
  app/src/main/java/com/example/teacherforboss/data/datasourceimpl.remote/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/example/teacherforboss/data/datasourceimpl.remote/MemberRemoteDataSourceImpl.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/auth/AccountResponseDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/auth/LogoutResponse.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/auth/WithdrawResponse.kt
  app/src/main/java/com/example/teacherforboss/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/service/AuthService.kt
  app/src/main/java/com/example/teacherforboss/data/service/MemberService.kt
  app/src/main/java/com/example/teacherforboss/di/DataSourceModule.kt
  app/src/main/java/com/example/teacherforboss/di/RepositoryModule.kt
  app/src/main/java/com/example/teacherforboss/di/RetrofitModule.kt
  app/src/main/java/com/example/teacherforboss/di/ServiceModule.kt
  app/src/main/java/com/example/teacherforboss/di/TokenManagerModule.kt
  app/src/main/java/com/example/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/example/teacherforboss/domain/model/auth/AccountEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/auth/LogoutResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/auth/WithdrawResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/MemberRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/Member/AccountUsecase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/auth/LogoutUsecase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/auth/WithdrawUsecase.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/auth/login/LoginActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/auth/login/LoginViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageAccountActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageAccountFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageAccountViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/mypage/ManageSocialAccountFragment.kt
  app/src/main/java/com/example/teacherforboss/util/base/LocalDataSource.kt
  app/src/main/res/layout/fragment_manage_account.xml
  app/src/main/res/layout/fragment_manage_social_account.xml
Labels: 🩷FEAT🩷, 혜원🐯

#73 [Feat] 홈 뷰 API 구현
  app/src/main/java/com/example/teacherforboss/data/datasource.remote/HomeRemoteDataSource.kt
  app/src/main/java/com/example/teacherforboss/data/datasourceimpl.remote/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/home/ResponseBossTalkPopularPostDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/home/ResponseTeacherTalkPopularPostDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/home/ResponseWeeklyBestTeacherDto.kt
  app/src/main/java/com/example/teacherforboss/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/service/HomeService.kt
  app/src/main/java/com/example/teacherforboss/di/DataSourceModule.kt
  app/src/main/java/com/example/teacherforboss/di/RepositoryModule.kt
  app/src/main/java/com/example/teacherforboss/di/ServiceModule.kt
  app/src/main/java/com/example/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/example/teacherforboss/domain/model/common/TeacherProfileDetailEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/home/BossTalkPopularPostEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/home/TeacherTalkPopularPostEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/home/WeeklyBestTeacherEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/HomeRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/home/GetBossTalkPopularPostUseCase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/home/GetTeacherTalkPopularPostUseCase.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/home/GetWeeklyBestTeacherUseCase.kt
  app/src/main/java/com/example/teacherforboss/presentation/type/KeywordType.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/common/TeacherProfileViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeBannerViewPagerAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeBossTalkPopularPostAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeBossTalkPopularPostViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeTeacherTalkPopularPostAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeTeacherTalkPopularPostViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherKeywordAdapter.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherKeywordViewHolder.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/home/HomeWeeklyBestTeacherViewHolder.kt
  app/src/main/res/layout/item_home_boss_talk_popular_post.xml
  app/src/main/res/layout/item_home_teacher_talk_popular_post.xml
  app/src/main/res/layout/item_home_weekly_best_teacher.xml
  app/src/main/res/layout/item_teacher_keyword.xml
Labels: 🩷FEAT🩷, 지은🎀

#82 Feat/search: 검색결과 뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teacherforboss/data/datasource.remote/CommunityRemoteDataSource.kt
  app/src/main/java/com/example/teacherforboss/data/datasourceimpl.remote/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/com/example/teacherforboss/data/model/request/community/teacher/RequestTeacherTalkQuestionsDto.kt
  app/src/main/java/com/example/teacherforboss/data/model/response/community/teacher/ResponseTeacherTalkQuestionsDto.kt
  app/src/main/java/com/example/teacherforboss/data/repository/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/teacherforboss/data/service/CommunityService.kt
  app/src/main/java/com/example/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/boss/BossTalkPostsResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/teacher/TeacherTalkQuestionsRequestEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/model/community/teacher/TeacherTalkQuestionsResponseEntity.kt
  app/src/main/java/com/example/teacherforboss/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/teacherforboss/domain/usecase/community/teacher/TeacherTalkSearchUseCase.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/main/BossTalkMainViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/main/basic/BossTalkMainFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/search/BossTalkSearchActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/boss_talk/search/rvAdapterCardBoss.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/main/TeacherTalkMainViewModel.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/main/basic/TeacherTalkMainFragment.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/search/TeacherTalkSearchActivity.kt
  app/src/main/java/com/example/teacherforboss/presentation/ui/community/teacher_talk/search/rvAdapterCardTeacher.kt
  app/src/main/java/com/example/teacherforboss/util/base/LocalDateFormatter.kt
  app/src/main/res/drawable/background_radius100_white.xml
  app/src/main/res/drawable/background_radius4_purple600.xml
  app/src/main/res/layout/activity_boss_talk_search.xml
  app/src/main/res/layout/activity_teacher_talk_search.xml
  app/src/main/res/layout/rv_item_boss_search_card.xml
  app/src/main/res/layout/rv_item_teacher_search_card.xml
Labels: 🩷FEAT🩷, 희재🐹
