Repository teacher-for-boss/teacher-for-boss-android, pull requests merged in 2024-10, with the labels that each got.

#187 Feat/#185
  app/src/main/java/com/company/teacherforboss/data/datasource.remote/AuthRemoteDataSource.kt
  app/src/main/java/com/company/teacherforboss/data/datasourceimpl.remote/AuthRemoteDataSourceImpl.kt
  app/src/main/java/com/company/teacherforboss/data/model/request/login/LoginRequest.kt
  app/src/main/java/com/company/teacherforboss/data/repositoryImpl/AuthRepositoryImpl.kt
  app/src/main/java/com/company/teacherforboss/data/service/AuthService.kt
  app/src/main/java/com/company/teacherforboss/domain/repository/AuthRepository.kt
  app/src/main/java/com/company/teacherforboss/domain/usecase/auth/LogoutUsecase.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/login/LoginActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/login/LoginViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/ProfileImageDialogFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/SignupActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/SignupViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/boss/BossProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/teacher/BusinessFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/auth/signup/teacher/TeacherProfileFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/body/adapter/rvAdapterCommentBoss.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/body/adapter/rvAdapterCommentTeacher.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/ManageAccountViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/modify/ProfileImageModifyDialogFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/notification/TFBFirebaseMessagingService.kt
  app/src/main/java/com/company/teacherforboss/util/base/LocalDataSource.kt
Labels: 🩷FEAT🩷, 혜원🐯

#186 [Fix/#184] 푸시알림API 및 댓글개수수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/company/teacherforboss/MainActivity.kt
  app/src/main/java/com/company/teacherforboss/data/datasource.remote/NotificationRemoteDataSource.kt
  app/src/main/java/com/company/teacherforboss/data/datasourceimpl.remote/NotificationRemoteDataSourceImpl.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/community/boss/ResponseBossTalkBodyDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/community/teacher/ResponseTeacherTalkBodyDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/notification/NotificationSettingDto.kt
  app/src/main/java/com/company/teacherforboss/data/repositoryImpl/NotificationRepositoryImpl.kt
  app/src/main/java/com/company/teacherforboss/data/service/NotificationService.kt
  app/src/main/java/com/company/teacherforboss/di/UseCaseModule.kt
  app/src/main/java/com/company/teacherforboss/domain/model/community/boss/BossTalkBodyResponseEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/community/teacher/TeacherTalkBodyResponseEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/notification/NotificationSettingEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/repository/NotificationRepository.kt
  app/src/main/java/com/company/teacherforboss/domain/usecase/notification/NotificationSettingGetUseCase.kt
  app/src/main/java/com/company/teacherforboss/domain/usecase/notification/NotificationSettingPostUseCase.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/boss_talk/body/BossTalkBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/community/teacher_talk/body/TeacherTalkBodyActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/NotificationFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/notification_setting/ManageNotificationActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/notification_setting/NotificationFragment.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/mypage/notification_setting/NotificationSettingViewModel.kt
  app/src/main/java/com/company/teacherforboss/util/base/LocalDataSource.kt
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️FIX🛠️, 🩷FEAT🩷, 희재🐹

#191 [Feat/#190] 알림리스트조회 API
  app/src/main/java/com/company/teacherforboss/data/datasource.remote/NotificationRemoteDataSource.kt
  app/src/main/java/com/company/teacherforboss/data/datasourceimpl.remote/NotificationRemoteDataSourceImpl.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/notification/NotificationDto.kt
  app/src/main/java/com/company/teacherforboss/data/model/response/notification/NotificationListDto.kt
  app/src/main/java/com/company/teacherforboss/data/repositoryImpl/NotificationRepositoryImpl.kt
  app/src/main/java/com/company/teacherforboss/data/service/NotificationService.kt
  app/src/main/java/com/company/teacherforboss/domain/model/notification/NotificationEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/model/notification/NotificationListEntity.kt
  app/src/main/java/com/company/teacherforboss/domain/repository/NotificationRepository.kt
  app/src/main/java/com/company/teacherforboss/domain/usecase/notification/NotificationUseCase.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/notification/NotificationActivity.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/notification/NotificationAdapter.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/notification/NotificationViewModel.kt
  app/src/main/java/com/company/teacherforboss/presentation/ui/notification/dummyNotificationEntity.kt
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/rv_item_notification.xml
  app/src/main/res/values/strings.xml
Labels: 🩷FEAT🩷, 희재🐹
